sonar.projectKey=${env.SONAR_PROJECT_KEY}
sonar.organization=${env.SONAR_ORGANIZATION}
sonar.projectName=eadesign-ca2

sonar.sources=BACK_END/src/main,FRONT_END
sonar.tests=BACK_END/src/test,FRONT_END/test

sonar.java.binaries=BACK_END/target/classes
sonar.exclusions=**/node_modules/**,**/target/**,**/dependency-check-report/**,**/*.min.js
