name: CI/CD Pipeline

on:
  workflow_dispatch

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # Docker Login
    - name: Login to Docker Hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    # Build Frontend
    - name: Build Frontend Image
      shell: powershell
      run: |
        cd FRONT_END
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

    # Build Backend
    - name: Build Backend Image
      shell: powershell
      run: |
        cd BACK_END
        mvn -B package --file pom.xml
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

    # Push Images
    - name: Push Frontend Image
      shell: powershell
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Push Backend Image
      shell: powershell
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    # Trivy Scan
    - name: Run Trivy Scan
      shell: powershell
      run: |
        docker run --rm aquasec/trivy:0.50.1 image ${{ secrets.DOCKER_USERNAME }}/backend:latest

    # Ensure Minikube Running
    - name: Ensure Minikube Running
      shell: powershell
      run: |
        minikube status
        if ($LASTEXITCODE -ne 0) {
          minikube start
        }

    # Wait for Kubernetes
    - name: Wait for Kubernetes
      shell: powershell
      run: |
        kubectl wait --for=condition=Ready nodes --all --timeout=120s

    # Set KUBECONFIG (correct fix)
    - name: Set KUBECONFIG
      shell: powershell
      run: |
        $env:KUBECONFIG="$HOME\.kube\config"

    # Verify cluster connection
    - name: Verify Cluster
      shell: powershell
      run: kubectl get nodes

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    # Terraform Plan
    - name: Terraform Plan
      shell: powershell
      run: |
        cd terraform
        terraform init
        terraform plan

    # Terraform Apply
    - name: Terraform Deploy
      shell: powershell
      run: |
        cd terraform
        terraform apply -auto-approve