name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v5

    # Docker Login

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin


    - name: Build Frontend Image
      run: |
        cd FRONT_END
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

 
    - name: Build Backend Image
      run: |
        cd BACK_END
        mvn -B package --file pom.xml
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

    
    # Trivy Scan

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ secrets.DOCKER_USERNAME }}/backend:latest'

   
    # Push Images

    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest


    